<a href="https://colab.research.google.com/github/jdasam/aat3020/blob/2026/notebooks/1_word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word2Vec Implementation from Scratch

This notebook demonstrates how to implement the Word2Vec algorithm from scratch using PyTorch. We'll use the first Harry Potter book as our corpus to train word embeddings.


## 1. Setting Up the Environment

First, we need to import the necessary libraries:
- `torch` and `torch.nn` for tensor operations and neural network functionality
- `string` for string manipulations (removing punctuation)


In [4]:
import torch
import torch.nn as nn
import string

## 2. Getting the Text Data

We'll download the first Harry Potter book to use as our corpus.

In [5]:
!wget "https://raw.githubusercontent.com/amephraim/nlp/master/texts/J.%20K.%20Rowling%20-%20Harry%20Potter%201%20-%20Sorcerer's%20Stone.txt"


--2026-03-17 05:14:25--  https://raw.githubusercontent.com/amephraim/nlp/master/texts/J.%20K.%20Rowling%20-%20Harry%20Potter%201%20-%20Sorcerer's%20Stone.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 439742 (429K) [text/plain]
Saving to: ‘J. K. Rowling - Harry Potter 1 - Sorcerer's Stone.txt’

J. K. Rowling - Har 100%[===================>] 429.44K  --.-KB/s    in 0.04s   

2026-03-17 05:14:25 (11.8 MB/s) - ‘J. K. Rowling - Harry Potter 1 - Sorcerer's Stone.txt’ saved [439742/439742]



## 3. Text Preprocessing

Before we can use the text data, we need to preprocess it:
- Remove punctuation
- Convert text to lowercase
- Split text into tokens (words)

This function will help us clean and tokenize the text.

In [6]:
def remove_punctuation(x):
  return x.translate(''.maketrans('', '', string.punctuation))

def make_tokenized_corpus(corpus):
  out= [ [y.lower() for y in remove_punctuation(sentence).split(' ') if y] for sentence in corpus]
  return [x for x in out if x!=[]]


## 4. Loading and Formatting the Text

Now we'll load the text file, replace some special characters, and split the text into sentences.


In [7]:
with open("J. K. Rowling - Harry Potter 1 - Sorcerer's Stone.txt", 'r') as f:
  strings = f.readlines()
sample_text = "".join(strings).replace('\n', ' ').replace('Mr.', 'mr').replace('Mrs.', 'mrs').split('. ')


In [8]:
sample_text

["Harry Potter and the Sorcerer's Stone   CHAPTER ONE  THE BOY WHO LIVED  mr and mrs Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much",
 "They were the last people you'd expect to be involved in anything strange or mysterious, because they just didn't hold with such nonsense",
 ' mr Dursley was the director of a firm called Grunnings, which made drills',
 'He was a big, beefy man with hardly any neck, although he did have a very large mustache',
 'mrs Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors',
 'The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere',
 ' The Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it',
 "They didn't think they could bear it if anyone found out ab

Let's tokenize the text using our preprocessing function `make_tokenized_corpus`:

In [9]:
# Corpus is a list of list of strings (words)

In [10]:
corpus = make_tokenized_corpus(sample_text)
corpus[10:15]

[['the',
  'dursleys',
  'knew',
  'that',
  'the',
  'potters',
  'had',
  'a',
  'small',
  'son',
  'too',
  'but',
  'they',
  'had',
  'never',
  'even',
  'seen',
  'him'],
 ['this',
  'boy',
  'was',
  'another',
  'good',
  'reason',
  'for',
  'keeping',
  'the',
  'potters',
  'away',
  'they',
  'didnt',
  'want',
  'dudley',
  'mixing',
  'with',
  'a',
  'child',
  'like',
  'that'],
 ['when',
  'mr',
  'and',
  'mrs',
  'dursley',
  'woke',
  'up',
  'on',
  'the',
  'dull',
  'gray',
  'tuesday',
  'our',
  'story',
  'starts',
  'there',
  'was',
  'nothing',
  'about',
  'the',
  'cloudy',
  'sky',
  'outside',
  'to',
  'suggest',
  'that',
  'strange',
  'and',
  'mysterious',
  'things',
  'would',
  'soon',
  'be',
  'happening',
  'all',
  'over',
  'the',
  'country'],
 ['mr',
  'dursley',
  'hummed',
  'as',
  'he',
  'picked',
  'out',
  'his',
  'most',
  'boring',
  'tie',
  'for',
  'work',
  'and',
  'mrs',
  'dursley',
  'gossiped',
  'away',
  'happily',


## 5. Creating Context Word Pairs

A key concept in Word2Vec is learning from context. We need to create pairs of words that appear near each other in the text. We'll use a sliding window approach to create these pairs.

For example, with the window size of 2, for the word "to" in the sentence "they were the last people youd expect to be involved...", we would create pairs with:
- ("to", "expect")
- ("to", "be")
- ("to", "involved")
- ("to", "in")

These pairs will be our training data.

In [11]:
from tqdm import tqdm

sample_sentence = ['they', 'were', 'the', 'last', 'people', 'youd', 'expect', 'to', 'be', 'involved', 'in', 'anything', 'strange', 'or', 'mysterious', 'because', 'they', 'just', 'didnt', 'hold', 'with', 'such', 'nonsense']

word_pairs = []
window_size = 2

for i, word in enumerate(sample_sentence):
  left_index = max(i - window_size, 0)
  right_index = min(i + window_size, len(sample_sentence) - 1)
  js = list(range(left_index, i)) +  list(range(i + 1, right_index + 1))
  # print(js)
  for j in js:
    word_pair = (word, sample_sentence[j])
    word_pairs.append(word_pair)


print(f"\nLength of word_pairs is {len(word_pairs)}")
print(f"First 5 example of word_pairs is {word_pairs[:5]}")


Length of word_pairs is 86
First 5 example of word_pairs is [('they', 'were'), ('they', 'the'), ('were', 'they'), ('were', 'the'), ('were', 'last')]


In [12]:
sample_text[0]

"Harry Potter and the Sorcerer's Stone   CHAPTER ONE  THE BOY WHO LIVED  mr and mrs Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much"

In [13]:
word_pairs = []
window_size = 2

for sample_sentence in tqdm(corpus):
  for i, word in enumerate(sample_sentence):
    left_index = max(i - window_size, 0)
    right_index = min(i + window_size, len(sample_sentence) - 1)
    js = list(range(left_index, i)) +  list(range(i + 1, right_index + 1))
    # print(js)
    for j in js:
      word_pair = (word, sample_sentence[j])
      word_pairs.append(word_pair)

100%|██████████| 4682/4682 [00:00<00:00, 25460.03it/s]


In [14]:
len(word_pairs)

282372

In [15]:
word_pairs[:10]

[('harry', 'potter'),
 ('harry', 'and'),
 ('potter', 'harry'),
 ('potter', 'and'),
 ('potter', 'the'),
 ('and', 'harry'),
 ('and', 'potter'),
 ('and', 'the'),
 ('and', 'sorcerers'),
 ('the', 'potter')]

## 6. Building the Vocabulary

To work with word vectors, we need to create a vocabulary that maps each unique word to an index. We'll also filter out rare words that appear less than a certain number of times in the corpus.

### 6.1 Collecting All Words

First, let's collect all words in our corpus:


In [16]:
# we have to make vocabulary

corpus[0:5]
entire_words = []
for sentence in corpus:
  for word in sentence:
    entire_words.append(word)

entire_words = [word for sentence in corpus for word in sentence]
len(entire_words)

77597


### 6.2 Finding Unique Words

Now, let's find the unique words in our corpus:

In [17]:
# we have to get the "unique" item among total words
len(set(entire_words))

from collections import Counter
word_counter = Counter(entire_words)
# item -> key of Counter
# number of occurence -> value of that key in Counter

threshold = 10
vocab = []
for key,value in word_counter.items():
  # print(key,value)
  if value >= threshold:
    vocab.append(key)
vocab.sort()
print(vocab)

['a', 'able', 'about', 'above', 'across', 'added', 'after', 'afternoon', 'again', 'against', 'ages', 'ago', 'agreed', 'ah', 'ahead', 'air', 'albus', 'all', 'allowed', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'an', 'and', 'angry', 'another', 'answer', 'any', 'anyone', 'anythin', 'anything', 'anyway', 'apart', 'appeared', 'are', 'arent', 'arm', 'arms', 'around', 'arrived', 'as', 'ask', 'asked', 'asleep', 'at', 'aunt', 'away', 'baby', 'back', 'bad', 'bag', 'ball', 'balls', 'bane', 'barrier', 'be', 'beard', 'became', 'because', 'bed', 'been', 'before', 'began', 'behind', 'being', 'believe', 'bent', 'best', 'bet', 'better', 'between', 'big', 'bin', 'birthday', 'bit', 'black', 'blood', 'bludgers', 'blue', 'boat', 'body', 'book', 'books', 'both', 'bottle', 'bought', 'boy', 'boys', 'break', 'breakfast', 'breath', 'bright', 'broke', 'broken', 'broom', 'brooms', 'broomstick', 'brothers', 'brought', 'burst', 'business', 'busy', 'but', 'buy', 'by', 'call', 'called

### 6.3 Converting to a List and Sorting

We'll convert the set of unique words to a sorted list:

In [18]:
# vocab_set[0] # set is not subscriptable because it has no order



### 6.4 Filtering by Frequency

Now, let's filter out rare words that occur less than a specified number of times:
- We can use the `Counter` class from the `collections` module to count the frequency of each word in the corpus.
- Caution on `alist.sort()` will return `None`.

In [19]:
# how can we filter the vocab by its frequency?
filtered_vocab = None
# you can use word counter as dictionary
# In python dictionary, dict.keys() gives keys, and dict.values() give values,
# dict.items() give (key, value)



## 7. Filtering Word Pairs

Now that we have our filtered vocabulary, we need to filter our word pairs to only include words that are in our vocabulary:
- in other words, we are going to exclude out-of-vocab words

In [20]:
# Filter the word_pairs using the vocab
# word_pairs, filtered_vocab
# word_pairs is a list of [word_a, word_b]
filtered_pairs = []
word_pairs[100:106]
pair = word_pairs[56]
center_word, context_word = pair
is_valid_pair = center_word in vocab and context_word in vocab
for pair in word_pairs:
  center_word, context_word = pair
  is_valid_pair = center_word in vocab and context_word in vocab
  if is_valid_pair:
    filtered_pairs.append(pair)

In [21]:
len(filtered_pairs)

205388

In [22]:
# implement same algorithm with list comprehension
filtered_pairs = [pair for pair in word_pairs if pair[0] in vocab and pair[1] in vocab]


In [23]:
filtered_pairs[34]

('boy', 'the')

## 8. Converting Words to Indices

For efficiency, we'll convert our words to indices according to their position in our vocabulary:

In [24]:
# convert word into index of vocab
sample_pair = filtered_pairs[34]
w1, w2 = sample_pair
vocab.index(w2)

import time

start_time = time.time()
pair_in_idx = [(vocab.index(pair[0]), vocab.index(pair[1])) for pair in filtered_pairs]
print(time.time() - start_time)

4.452696084976196


This is inefficient because `list.index()` has to scan the list every time. Let's use a dictionary for faster lookups:

In [25]:
# we can make it faster
# use dictionary to find the index of string

# a dictionary that has word as key, and index_of_word as value
word2idx = {}
for i,word in enumerate(vocab):
  word2idx[word] = i
word2idx

{'a': 0,
 'able': 1,
 'about': 2,
 'above': 3,
 'across': 4,
 'added': 5,
 'after': 6,
 'afternoon': 7,
 'again': 8,
 'against': 9,
 'ages': 10,
 'ago': 11,
 'agreed': 12,
 'ah': 13,
 'ahead': 14,
 'air': 15,
 'albus': 16,
 'all': 17,
 'allowed': 18,
 'almost': 19,
 'alone': 20,
 'along': 21,
 'already': 22,
 'also': 23,
 'although': 24,
 'always': 25,
 'am': 26,
 'an': 27,
 'and': 28,
 'angry': 29,
 'another': 30,
 'answer': 31,
 'any': 32,
 'anyone': 33,
 'anythin': 34,
 'anything': 35,
 'anyway': 36,
 'apart': 37,
 'appeared': 38,
 'are': 39,
 'arent': 40,
 'arm': 41,
 'arms': 42,
 'around': 43,
 'arrived': 44,
 'as': 45,
 'ask': 46,
 'asked': 47,
 'asleep': 48,
 'at': 49,
 'aunt': 50,
 'away': 51,
 'baby': 52,
 'back': 53,
 'bad': 54,
 'bag': 55,
 'ball': 56,
 'balls': 57,
 'bane': 58,
 'barrier': 59,
 'be': 60,
 'beard': 61,
 'became': 62,
 'because': 63,
 'bed': 64,
 'been': 65,
 'before': 66,
 'began': 67,
 'behind': 68,
 'being': 69,
 'believe': 70,
 'bent': 71,
 'best': 72,
 '

Now, let's convert our word pairs to index pairs more efficiently:

In [26]:
start_time = time.time()
pair_in_idx = [(word2idx[pair[0]], word2idx[pair[1]]) for pair in filtered_pairs]
print(time.time() - start_time)


0.062166690826416016


In [27]:
# Why we don't need idx2tok?
vocab[671]


'quaffle'

## 9. Creating Initial Word Vectors

Now we'll create random vectors for each word in our vocabulary. These vectors will be adjusted during training:
- We can use `torch.randn` to create random vectors that follow normal distribution.

In [53]:
# we have to make random vectors for each word in the vocab
# we also have to decide the dimension of the vector
len(vocab)
vector_size = 4

wordvecs = torch.randn(len(vocab), vector_size) / vector_size

In [54]:
# what is the vector for harry?

wordvecs[word2idx['harry']]

tensor([-0.1280,  0.1069,  0.3375,  0.3532])

## 10. Understanding Word Relationships with Dot Products

The core of Word2Vec is using dot products to measure relationships between words. Let's explore this concept:

In [55]:
torch.set_printoptions(sci_mode=False) # Do this to avoid scientific notation

## Dot Product
- Assume we have two vectors $a$ and $b$.
  - $a = [a_1, a_2, a_3, a_4, ..., a_n]$
  - $b = [b_1, b_2, b_3, b_4, ..., b_n]$
- $a \cdot b$ = $\sum _{i=1}^n a_ib_i$  = $a_1b_1 + a_2b_2 + a_3b_3 + a_4b_4 + ... + a_nb_n$

Let's calculate the dot product between "harry" and "potter":


In [56]:
# calculate P(potter|harry)

harry = wordvecs[word2idx['harry']]
potter = wordvecs[word2idx['potter']]
harry, potter

# harry @ potter
(harry * potter).sum()

tensor(-0.1743)

In [57]:
wordvecs.shape, harry.shape

(torch.Size([1035, 4]), torch.Size([4]))

In [58]:
# we can get the dot product value for every other words in the vocab
# to get  P(word | harry)

# for vector in wordvecs:
#   (vector * harry).sum()

dotprods = (wordvecs * harry).sum(dim = 1)
dotprods[word2idx['potter']]

tensor(-0.1743)

Now, let's convert these dot products to probabilities using the softmax function:
- We have to convert our prediction into probability distribution to get P(word|harry) so that sum of [P(a|harry), ..., P(potter|harry), ... P(ron|harry), ... ] = 1
- current dot product value is any real number, sometimes called as logit
  - logit from logistic regression. Some values that are not yet converted to 0-1 or value before sigmoid function
  - every probability should be in range (0, 1) (greater than 0, smaller than 1)
  - this can be handled by taking exponential of dot product values, divided by total sum
  - This function is called **Softmax**

- Why we use exponential?
  - Because we want to make every probability in positive range while preserving the order


In [59]:
from math import exp

dotprods.exp() / dotprods.exp().sum()

tensor([0.0008, 0.0008, 0.0010,  ..., 0.0009, 0.0010, 0.0009])

In [60]:
# Get P(potter|harry)
print(dotprods)
print(dotprods.shape)

exp_dotprods = dotprods.exp()
print(exp_dotprods)

print(exp_dotprods.sum())

# prob_dist =
# prob_dist.sum() == 1
prob_dist = exp_dotprods / exp_dotprods.sum()
print(prob_dist)
print(prob_dist.sum())

tensor([-0.2078, -0.2010,  0.0340,  ..., -0.0373,  0.0174, -0.1024])
torch.Size([1035])
tensor([0.8124, 0.8179, 1.0346,  ..., 0.9634, 1.0176, 0.9026])
tensor(1042.9277)
tensor([0.0008, 0.0008, 0.0010,  ..., 0.0009, 0.0010, 0.0009])
tensor(1.)


In [61]:
# P(potter | harry)
prob_dist[word2idx['potter']]

tensor(0.0008)

## 13. Efficient Matrix Operations
![img](https://mkang32.github.io/images/python/khan_academy_matrix_product.png)

Instead of calculating dot products one by one, we can use matrix multiplication for efficiency:


In [ ]:
harry, potter


In [68]:
# get dot product result for every word in the vocabulary

# first, make vector_of_harry into matrix format
harry = wordvecs[word2idx['harry']]
print(harry.shape, harry)
harry = harry.reshape([1, -1])
print(harry.shape, harry)

# do matrix multiplication
matmul = wordvecs @ harry.T

torch.Size([4]) tensor([-0.1280,  0.1069,  0.3375,  0.3532])
torch.Size([1, 4]) tensor([[-0.1280,  0.1069,  0.3375,  0.3532]])


Let's verify that our matrix multiplication gives the same result as individual dot products:

In [70]:
matmul.shape, dotprods.shape

(torch.Size([1035, 1]), torch.Size([1035]))

In [71]:
matmul.squeeze() == dotprods

tensor([ True,  True,  True,  ...,  True, False,  True])

In [73]:
matmul.squeeze(), dotprods

(tensor([-0.2078, -0.2010,  0.0340,  ..., -0.0373,  0.0174, -0.1024]),
 tensor([-0.2078, -0.2010,  0.0340,  ..., -0.0373,  0.0174, -0.1024]))

In [74]:
torch.allclose(matmul.squeeze(), dotprods)

True

In [78]:
harry = wordvecs[word2idx['harry']]
potter = wordvecs[word2idx['potter']]

harrypotter = torch.stack([harry, potter])
wordvecs @ harrypotter.T

tensor([[-0.2078,  0.3454],
        [-0.2010,  0.2360],
        [ 0.0340, -0.0591],
        ...,
        [-0.0373,  0.0024],
        [ 0.0174, -0.1582],
        [-0.1024,  0.0791]])

Now let's implement the complete softmax calculation using matrix operations:


In [ ]:
# convert dot product result into exponential


In [ ]:
# get the sum of exponential


tensor([1514.6581, 1509.8632])

In [ ]:
# divide exponential value with sum


## 14. Creating a Probability Function

Let's create a function to calculate probabilities efficiently:

## 15. Preparing for Training

Before training our Word2Vec model, we need to split our dataset into training and testing sets:

In [ ]:
# Now we can train the word2vec
import random
# Let's think about training pairs
index_pairs # this is our dataset. It's list of list of two integer

# two integer means a pair of neighboring words

# Training set and Test set
# To validate that our model can solve 'unseen' problems
# So we have to split the dataset before training.

# To randomly split the dataset, we will first shuffle the dataset



## 16. Training the Word2Vec Model

Now we'll train our Word2Vec model using batched gradient descent:

In [ ]:
# making batch from train_set
# Batch is a set of training samples, that are calculated together
# And also we update the model after one single batch


torch.Size([1506, 20])

In [ ]:
# plot vectors
center_words_vectors.shape
import matplotlib.pyplot as plt
plt.imshow(center_words_vectors.detach())

#### Training of torch
- Divide it in batch level
- for each batch:
  - calculate model prediction
  - calculate the loss
  - backprop the loss
  - update the parameters using gradient
  - repeat

In [ ]:
# define batch-wise training

In [ ]:
# train with for loop


In [ ]:
from tqdm.auto import tqdm



In [ ]:
# define validation function
def validate(model,test_set):
    loss = update_word_vectors(center_words,context_words,word_vectors, learning_rate=0.1,return_loss_only=True)
    loss_record.append(loss)


## 17. Evaluating the Training

Let's visualize the training loss to see if our model is learning:

## 18. Testing the Model

Now we'll test our model on the test set:

## 19. Exploring Learned Word Relationships

Let's explore what our model has learned by finding the words most closely related to "harry":

In [ ]:
# P(potter|harry)?
